In [1]:
import torch
import numpy

In [4]:
A01_x = torch.tensor([1, -1, 2])
A01_y = torch.tensor([0, 3, 1])
print(A01_x + A01_y)

tensor([1, 2, 3])


In [8]:
A02_x = torch.tensor([[1,2,3], [4,5,6]])
A02_y = torch.tensor([[-1, 0, 1]])
print(A02_x + A02_y)
print(A02_x[0] + A02_y)
print(A02_x[1] + A02_y)

tensor([[0, 2, 4],
        [3, 5, 7]])
tensor([[0, 2, 4]])
tensor([[3, 5, 7]])


In [12]:
A03_x = torch.tensor([[1,2,3], [4,5,6]])
A03_y = torch.tensor([[10], [20]])
print(A03_x + A03_y)

tensor([[11, 12, 13],
        [24, 25, 26]])


In [13]:
M11_x = torch.tensor([[1,2], [3,4]])
M11_y = torch.tensor([[2, 0], [1, 1]])
print(M11_x @ M11_y)

tensor([[ 4,  2],
        [10,  4]])


In [15]:
M12_x = torch.tensor([[1, 0, 2], [0, 1, 1]])
M12_y = torch.tensor([[2, 1], [1, 0], [0,1]])
print(M12_x @ M12_y)

tensor([[2, 3],
        [1, 1]])
